//
//  ViewController.m
//  ProjectEuler
//
//  Created by Nina on 04/03/15.
//  Copyright (c) 2015 Learn. All rights reserved.
//

#import "ViewController.h"
#import "NSArray+RangeArray.h"
#import "NSString+Split.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib
    [self.view setBackgroundColor:[UIColor whiteColor]];
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self sumOfPrimes];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark - Problem #1
//If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
//Find the sum of all the multiples of 3 or 5 below 1000.
- (void)getTotalOfNumbersDividibleBy3n5 {
    
    NSArray * numbers = [NSArray arrayWithNumbersInRange:NSMakeRange(0, 999)];
    int total = 0;
    for( NSNumber * number in numbers ){
        int no = [number unsignedIntValue];
        if ((no % 3 == 0) || (no % 5 == 0)) {
            total += no;
        }
    }
    NSLog(@"%i",total);
}

#pragma mark - Problem #2
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
- (void)fibonacciAdditionOfEvenValued {//4613732
    
    int fib1 = 1;
    int fib2 = 1;
    int result = 0;
    int summed = 0;
    
    while (result < 4000000) {
        if ((result % 2) == 0) {
            summed += result;
        }
        
        result = fib1 + fib2;
        fib2 = fib1;
        fib1 = result;
    }
    NSLog(@"summed %i", summed);
}

#pragma mark - Problem #3
/* The prime factors of 13195 are 5, 7, 13 and 29.
 What is the largest prime factor of the number 600851475143 ?*/
- (void)primeNumber {//6857

    int result;
    long input = 600851475143;
    
    for (result = 2; result < input; result ++) {
        if (input % result == 0) { //if the value is dividable by result, divide it to continue
            input /= result; //Neglect the divided value
            result --;
        }
    }
    NSLog(@"result %i", result);
}

#pragma mark - Problem #4
/* A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
 Find the largest palindrome made from the product of two 3-digit numbers.*/
- (void)largestPalindrome {//906609
    
    int largest = 0;
    int smallest = 999999;
    
    NSArray * numbers   =   [NSArray arrayWithNumbersInRange:NSMakeRange(100, 899)];
    
    for (int i = (int)numbers.count - 1; i >= 0; i --) {//Issue? will it multiply with itself?
        for (int j = (int)numbers.count - 1; j >= 0; j--) {
            int a = [numbers[i] intValue];
            int b = [numbers[j] intValue];
            int mul = a * b;
            
            //Ref: http://stackoverflow.com/questions/17946649/check-if-string-is-palindrome-in-objective-c
            NSString *p = [NSString stringWithFormat:@"%i", mul];
            NSInteger length = p.length;
            
            NSInteger halfLength = length / 2;
            
            __block BOOL isPalindrome = YES;
            
            [p enumerateSubstringsInRange:NSMakeRange(0, halfLength) options:NSStringEnumerationByComposedCharacterSequences usingBlock:^(NSString *substring, NSRange substringRange, NSRange enclosingRange, BOOL *stop) {
                NSRange otherRange = [p rangeOfComposedCharacterSequenceAtIndex:length - enclosingRange.location - 1];
                
                if (![substring isEqualToString:[p substringWithRange:otherRange]]) {
                    isPalindrome = NO;
                    *stop = YES;
                }
            }];
            if (isPalindrome) {
                if ([p intValue] > largest) {
                    largest = [p intValue];
                }
                if ([p intValue] < smallest) {
                    smallest = [p intValue];
                }
            }
        }
    }
    NSLog(@"largest = %i & smallest = %i", largest, smallest);
}

#pragma mark - Problem #5
/*2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
 What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?*/
- (void)smallestDivider {//232792560
    
    NSArray * numbers   =   [NSArray arrayWithNumbersInRange:NSMakeRange(1, 19)];
    NSNumber *sum       =   [numbers valueForKeyPath:@"@sum.self"];
    double maxLimit     =   pow([sum doubleValue], 20.0);
    
    for (int limit = 20; limit <= maxLimit; limit ++) {
        int modulo = 0;
        for (NSNumber *divider in numbers) {
            modulo  +=  limit % [divider intValue];
        }
        if (modulo == 0) {
            NSLog(@"Result %i", limit);
            break;
        }
    }
}

#pragma mark - Problem #6
/* The sum of the squares of the first ten natural numbers is,
 12 + 22 + ... + 102 = 385
 The square of the sum of the first ten natural numbers is,
 (1 + 2 + ... + 10)2 = 552 = 3025
 Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.
 Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.
*/
- (void)squareDifference {//25164150

    NSArray * numbers   =   [NSArray arrayWithNumbersInRange:NSMakeRange(1, 99)];
    NSNumber *sum       =   [numbers valueForKeyPath:@"@sum.self"];
    double sumSquare    =   pow([sum doubleValue], 2.0);
    
    NSArray *squaredNumbers =   [NSArray arrayWithSquaredNumbersInRange:NSMakeRange(1, 99)];
    NSNumber    *squaredSum =   [squaredNumbers valueForKeyPath:@"@sum.self"];
    
    double difference  =   sumSquare - [squaredSum doubleValue];
    NSLog(@"difference %.0f", difference);
}

#pragma mark - Problem #7
/* By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
 What is the 10001st prime number?
*/
- (void)primeNumberAtPosition {//104743
    
    //takes too long time to complete....
    NSInteger maxLimit              =   10001;
    NSMutableArray *primeNumbers    =   [NSMutableArray arrayWithCapacity:maxLimit];
    int i = 2; //smallest palindrome
    BOOL isPrime;
    int divi = 2;
    
    do {
        isPrime = YES;
        for (divi = 2; divi < i; divi++) {
            if (i % divi == 0) {
                isPrime = NO;
                continue;
            }
        }
        if (isPrime)
            [primeNumbers addObject:[NSNumber numberWithInt:i]];
        i++;

    } while ([primeNumbers count] < maxLimit);
    NSLog(@"%lu-st prime number %i", (unsigned long)primeNumbers.count, [[primeNumbers lastObject] intValue]);
}

#pragma mark - Problem #8
/* Largest product in a series
 
 The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.
 
 73167176531330624919225119674426574742355349194934
 96983520312774506326239578318016984801869478851843
 85861560789112949495459501737958331952853208805511
 12540698747158523863050715693290963295227443043557
 66896648950445244523161731856403098711121722383113
 62229893423380308135336276614282806444486645238749
 30358907296290491560440772390713810515859307960866
 70172427121883998797908792274921901699720888093776
 65727333001053367881220235421809751254540594752243
 52584907711670556013604839586446706324415722155397
 53697817977846174064955149290862569321978468622482
 83972241375657056057490261407972968652414535100474
 82166370484403199890008895243450658541227588666881
 16427171479924442928230863465674813919123162824586
 17866458359124566529476545682848912883142607690042
 24219022671055626321111109370544217506941658960408
 07198403850962455444362981230987879927244284909188
 84580156166097919133875499200524063689912560717606
 05886116467109405077541002256983155200055935729725
 71636269561882670428252483600823257530420752963450
 Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?
 */

-(void)largestProductInSeries {//23514624000
    
    NSString *given =   @"7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450";
    
    int numberOfDigits = 13;
    int difference = (int)given.length - numberOfDigits;
    long max = 0;
    
    for ( int i = 0 ; i <= difference ; i++ ) {
        
        long product = 1;
        int compare = i + numberOfDigits;
        
        for ( int j = i ; j < compare ; j++ ) {
            
            NSArray *singleDigits   =   [given arrayBySplittingWithMaximumSize:1];
            int digit   =   [singleDigits[j] intValue];
            if (digit == 0)
                break;
            product *= digit;
        }
        if ( product > max ) {
            max = product;
        }
    }
    
    NSLog(@"answer %li", (long)max);
}

#pragma mark - Problem #9

/*A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
 
 a2 + b2 = c2
 For example, 32 + 42 = 9 + 16 = 25 = 52.
 
 There exists exactly one Pythagorean triplet for which a + b + c = 1000.
 Find the product abc.*/
- (void)findTripletProduct {//31875000
    
    int a = 0, b = 0, c = 0;
    int s = 1000;
    bool found = false;
    for (a = 1; a < s / 3; a++) {
        for (b = a; b < s / 2; b++) {
            c = s - a - b;
            
            if (a * a + b * b == c * c) {
                found = true;
                break;
            }
        }
        
        if (found) {
            break;
        }
    }
    int product = a * b * c;
    NSLog(@"%i", product);
}

#pragma mark - Problem #10
/*Problem 10
Published on Friday, 8th February 2002, 11:30 pm; Solved by 176486
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
Find the sum of all the primes below two million.*/
- (void)sumOfPrimes {//142913828922
    
    //Sieve of Eratosthenes algorithm to find prime numbers
    int maxLimit              =   2000000;
    NSMutableArray *list    =   [NSMutableArray arrayWithNumbersInRange:NSMakeRange(0, maxLimit)];
    list[1] =   [NSNumber numberWithInt:0];
    
    int p   =   2;
    while (pow(p, 2) <= maxLimit) {
     
        int j   =   pow(p, 2);
        
        while (j <= maxLimit) {
            
            list[j] =   [NSNumber numberWithInt:0];//replace non-prime numbers with '0'
            j       +=  p;
        }
        if ([list[p] integerValue] !=  1)
            p   ++;
    }
    NSLog(@"result %@", [list valueForKeyPath:@"@sum.self"]);
}

@end
